"""
Auto-generated tests for realtime_emotion_monitor.py
Generated by HUMAN 2.0 TestGenerator using Claude 3.5 Sonnet
"""

import pytest
from unittest.mock import Mock, patch, MagicMock
from collections import deque
from realtime_emotion_monitor import EmotionHistory, AudioCapture

class TestEmotionHistory:
    @pytest.fixture
    def emotion_history(self):
        """Fixture for EmotionHistory"""
        return EmotionHistory(deque(), deque())

    def test_add_emotion_success(self, emotion_history):
        """Test successful addition of emotion"""
        # Arrange
        emotion = 'happy'
        confidence = 0.8
        timestamp = 1627924800.0  # Arbitrary timestamp
        # Act
        emotion_history.add_emotion(emotion, confidence, timestamp)
        # Assert
        assert emotion_history.emotions[-1] == (emotion, confidence)
        assert emotion_history.timestamps[-1] == timestamp

    def test_get_recent_emotions_success(self, emotion_history):
        """Test successful retrieval of recent emotions"""
        # Arrange
        emotion_history.add_emotion('happy', 0.8, time.time() - 10)  # 10 seconds ago
        emotion_history.add_emotion('sad', 0.6, time.time() - 40)  # 40 seconds ago
        # Act
        recent_emotions = emotion_history.get_recent_emotions(30)
        # Assert
        assert len(recent_emotions) == 1
        assert recent_emotions[0] == ('happy', 0.8)

    def test_get_emotion_trend_success(self, emotion_history):
        """Test successful computation of emotion trend"""
        # Arrange
        emotion_history.add_emotion('happy', 0.8, time.time() - 10)
        emotion_history.add_emotion('happy', 0.7, time.time() - 20)
        emotion_history.add_emotion('sad', 0.6, time.time() - 30)
        # Act
        emotion_trend = emotion_history.get_emotion_trend()
        # Assert
        assert emotion_trend == {'happy': 0.75, 'sad': 0.6}


class TestAudioCapture:
    @pytest.fixture
    def audio_capture(self):
        """Fixture for AudioCapture"""
        return AudioCapture()

    @patch('realtime_emotion_monitor.pyaudio.PyAudio')
    def test_init_success(self, mock_pyaudio, audio_capture):
        """Test successful initialization of AudioCapture"""
        # Assert
        assert audio_capture.sample_rate == 22050
        assert audio_capture.chunk_size == 1024
        assert audio_capture.channels == 1
        assert isinstance(audio_capture.audio_queue, queue.Queue)
        assert audio_capture.is_recording == False
        assert isinstance(audio_capture.audio_buffer, deque)
        assert audio_capture.audio_buffer.maxlen == 50
        mock_pyaudio.assert_called_once()