"""
Auto-generated tests for agi_orchestrator.py
Generated by HUMAN 2.0 TestGenerator using Claude 3.5 Sonnet
"""

import pytest
from unittest.mock import Mock, patch
from src.core.agi_orchestrator import AGIOrchestrator

class TestAGIOrchestrator:
    @pytest.fixture
    def agi_orchestrator(self):
        """Fixture for creating AGIOrchestrator instance"""
        return AGIOrchestrator()

    @patch('os.path.exists')
    @patch('json.load')
    def test_load_config_success(self, mock_json_load, mock_exists, agi_orchestrator):
        """Test successful load of configuration"""
        # Arrange
        mock_exists.return_value = True
        mock_json_load.return_value = {'improvement_interval_hours': 24}

        # Act
        result = agi_orchestrator._load_config('config.json')

        # Assert
        assert result['improvement_interval_hours'] == 24

    @patch('os.path.exists')
    def test_load_config_file_not_found(self, mock_exists, agi_orchestrator):
        """Test load config when file does not exist"""
        # Arrange
        mock_exists.return_value = False

        # Act
        result = agi_orchestrator._load_config('config.json')

        # Assert
        assert result['improvement_interval_hours'] == 24

    @patch('os.path.exists')
    @patch('json.load')
    def test_load_config_json_load_error(self, mock_json_load, mock_exists, agi_orchestrator):
        """Test load config when json load throws an error"""
        # Arrange
        mock_exists.return_value = True
        mock_json_load.side_effect = Exception()

        # Act
        with pytest.raises(Exception):
            agi_orchestrator._load_config('config.json')