"""
Auto-generated tests for code_analyzer.py
Generated by HUMAN 2.0 TestGenerator using Claude 3.5 Sonnet
"""

import pytest
import ast
import logging
import tempfile
from unittest.mock import Mock, patch
from code_analyzer import CodeAnalyzer

class TestCodeAnalyzer:
    @pytest.fixture
    def code_analyzer(self):
        """Fixture for creating a CodeAnalyzer instance."""
        return CodeAnalyzer()

    @pytest.fixture
    def sample_code(self):
        """Fixture for sample Python code."""
        return "def hello_world():\n    print('Hello, world!')"

    @pytest.fixture
    def temp_file_path(self, sample_code):
        """Fixture for creating a temporary file."""
        with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as temp_file:
            temp_file.write(sample_code)
            return temp_file.name

    def test_analyze_code_success(self, code_analyzer, sample_code, temp_file_path):
        """Test successful case of analyze_code method."""
        # Arrange
        expected_result = {
            'success': True,
            'metrics': {},
            'issues': [],
            'ast_info': {},
            'error': None
        }

        # Act
        result = code_analyzer.analyze_code(sample_code)

        # Assert
        assert result == expected_result

    def test_analyze_code_error_case(self, code_analyzer):
        """Test error handling in analyze_code method."""
        # Arrange
        faulty_code = "def hello_world():\nprint('Hello, world!')"  # Indentation error

        # Act
        result = code_analyzer.analyze_code(faulty_code)

        # Assert
        assert result['success'] == False
        assert 'error' in result

    def test_compute_metrics_success(self, code_analyzer, sample_code):
        """Test successful case of _compute_metrics method."""
        # Arrange
        expected_result = {
            'num_functions': 1,
            'num_classes': 0,
            'num_imports': 0,
            'num_lines': 2,
        }

        # Act
        result = code_analyzer._compute_metrics(sample_code)

        # Assert
        assert result == expected_result

    def test_compute_metrics_error_case(self, code_analyzer):
        """Test error handling in _compute_metrics method."""
        # Arrange
        faulty_code = "def hello_world():\nprint('Hello, world!')"  # Indentation error

        # Act
        with pytest.raises(Exception):
            code_analyzer._compute_metrics(faulty_code)